spring:
  datasource:
      url: jdbc:mysql://localhost:3306/Cloudp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&connectTimeout=10000&socketTimeout=60000
      username: root
      password: Zxcv1234.
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
server:
   port: 8002
mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.jay.cloud.domain